import React from 'react';
import ReactDOM from 'react-dom';
/**
 * Inject scss generated by tailwind
 * 
 * This file is generated and not commited to version control
 */
import './generated.scss';
import App from './App';
import * as serviceWorker from './serviceWorker';

const root = document.getElementById('root');

root && root.hasChildNodes() ?
  ReactDOM.hydrate(<App />, root) :
  ReactDOM.render(<App/>, root);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
